"""add all missing columns to match model definitions

Revision ID: 132971c1d456
Revises: 4481595c5f02
Create Date: 2025-07-31 19:03:22.963930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132971c1d456'
down_revision = '4481595c5f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Modify product_sku table
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('barcode_type', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('unique_barcode', ['barcode'])
        batch_op.create_unique_constraint('unique_upc', ['upc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.drop_constraint('unique_upc', type_='unique')
        batch_op.drop_constraint('unique_barcode', type_='unique')
        batch_op.drop_column('barcode')
        batch_op.drop_column('barcode_type')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('cost_per_unit')

    # ### end Alembic commands ###