"""add all missing columns to match model definitions

Revision ID: 132971c1d456
Revises: 4481595c5f02
Create Date: 2025-07-31 19:03:22.963930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132971c1d456'
down_revision = '4481595c5f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_barcode', ['barcode'])
        batch_op.create_unique_constraint('unique_upc', ['upc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.drop_constraint('unique_upc', type_='unique')
        batch_op.drop_constraint('unique_barcode', type_='unique')

    # ### end Alembic commands ###
