
"""add all missing columns to match model definitions

Revision ID: 132971c1d456
Revises: 4481595c5f02
Create Date: 2025-07-31 19:03:22.963930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132971c1d456'
down_revision = '4481595c5f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, add all missing columns to product_sku table
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        # Add missing columns from ProductSKU model
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_label', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sku_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fifo_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retail_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_margin_target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_product_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_discontinued', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('supplier_sku', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('supplier_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_unit', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('barcode_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('upc', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('quality_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('quality_checked_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quality_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('temperature_at_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shopify_product_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('shopify_variant_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('etsy_listing_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('amazon_asin', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('marketplace_sync_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('marketplace_last_sync', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_perishable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=True))

        # Add foreign key constraints
        batch_op.create_foreign_key('fk_product_sku_variant', 'product_variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_batch', 'batch', ['batch_id'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_container', 'inventory_item', ['container_id'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_created_by', 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_quality_checked_by', 'user', ['quality_checked_by'], ['id'])

        # Now add unique constraints (after columns exist)
        batch_op.create_unique_constraint('unique_barcode', ['barcode'])
        batch_op.create_unique_constraint('unique_upc', ['upc'])

    # Add missing ProductSKUHistory table columns  
    with op.batch_alter_table('product_sku_history', schema=None) as batch_op:
        # Update the foreign key reference
        batch_op.add_column(sa.Column('inventory_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remaining_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('customer', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('fifo_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('fifo_reference_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fifo_source', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_perishable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reservation_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_reserved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sale_location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('quantity_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('batch_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('lot_number', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('temperature_at_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('quality_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('quality_checked_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marketplace_order_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('marketplace_source', sa.String(length=32), nullable=True))

        # Add foreign key constraints
        batch_op.create_foreign_key('fk_product_sku_history_inventory_item', 'inventory_item', ['inventory_item_id'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_history_container', 'inventory_item', ['container_id'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_history_created_by', 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_history_quality_checked_by', 'user', ['quality_checked_by'], ['id'])
        batch_op.create_foreign_key('fk_product_sku_history_fifo_reference', 'product_sku_history', ['fifo_reference_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop ProductSKUHistory additions
    with op.batch_alter_table('product_sku_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_sku_history_fifo_reference', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_history_quality_checked_by', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_history_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_history_container', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_history_inventory_item', type_='foreignkey')
        
        # Drop columns
        batch_op.drop_column('marketplace_source')
        batch_op.drop_column('marketplace_order_id')
        batch_op.drop_column('quality_checked_by')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('quality_status')
        batch_op.drop_column('location_name')
        batch_op.drop_column('location_id')
        batch_op.drop_column('temperature_at_time')
        batch_op.drop_column('lot_number')
        batch_op.drop_column('batch_number')
        batch_op.drop_column('quantity_used')
        batch_op.drop_column('sale_location')
        batch_op.drop_column('is_reserved')
        batch_op.drop_column('reservation_id')
        batch_op.drop_column('order_id')
        batch_op.drop_column('created_by')
        batch_op.drop_column('note')
        batch_op.drop_column('notes')
        batch_op.drop_column('container_id')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('shelf_life_days')
        batch_op.drop_column('is_perishable')
        batch_op.drop_column('fifo_source')
        batch_op.drop_column('fifo_reference_id')
        batch_op.drop_column('fifo_code')
        batch_op.drop_column('customer')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('remaining_quantity')
        batch_op.drop_column('inventory_item_id')

    # Drop ProductSKU additions
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.drop_constraint('unique_upc', type_='unique')
        batch_op.drop_constraint('unique_barcode', type_='unique')
        batch_op.drop_constraint('fk_product_sku_quality_checked_by', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_container', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_batch', type_='foreignkey')
        batch_op.drop_constraint('fk_product_sku_variant', type_='foreignkey')
        
        # Drop all added columns
        batch_op.drop_column('shelf_life_days')
        batch_op.drop_column('is_perishable')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('marketplace_last_sync')
        batch_op.drop_column('marketplace_sync_status')
        batch_op.drop_column('amazon_asin')
        batch_op.drop_column('etsy_listing_id')
        batch_op.drop_column('shopify_variant_id')
        batch_op.drop_column('shopify_product_id')
        batch_op.drop_column('temperature_at_time')
        batch_op.drop_column('location_name')
        batch_op.drop_column('location_id')
        batch_op.drop_column('quality_checked_at')
        batch_op.drop_column('quality_checked_by')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('quality_status')
        batch_op.drop_column('upc')
        batch_op.drop_column('barcode_type')
        batch_op.drop_column('barcode')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('weight_unit')
        batch_op.drop_column('weight')
        batch_op.drop_column('supplier_cost')
        batch_op.drop_column('supplier_sku')
        batch_op.drop_column('supplier_name')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_discontinued')
        batch_op.drop_column('is_product_active')
        batch_op.drop_column('tags')
        batch_op.drop_column('subcategory')
        batch_op.drop_column('category')
        batch_op.drop_column('profit_margin_target')
        batch_op.drop_column('wholesale_price')
        batch_op.drop_column('retail_price')
        batch_op.drop_column('container_id')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('fifo_id')
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('unit')
        batch_op.drop_column('sku_name')
        batch_op.drop_column('size_label')
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
