"""add type field to inventory_item

Revision ID: 1914edb5f281
Revises: 54ff2c76e2e5
Create Date: 2025-06-24 22:00:13.608065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1914edb5f281'
down_revision = '54ff2c76e2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('type', sa.String(length=32), nullable=True))
    
    # Update existing records with default value
    op.execute("UPDATE inventory_item SET type = 'ingredient' WHERE type IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
