"""empty message

Revision ID: 221660bdb3d5
Revises: 0005_cleanup_guardrails
Create Date: 2025-10-23 17:48:45.170441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221660bdb3d5'
down_revision = '0005_cleanup_guardrails'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('product_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('source_fifo_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('source_fifo_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('product_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
