"""add container tracking fields to batch containers

Revision ID: 241e744a7678
Revises: f1f26618e8e2
Create Date: 2025-06-27 17:47:37.664202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241e744a7678'
down_revision = 'f1f26618e8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity_used', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cost_each', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory_item', ['container_id'], ['id'])

    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity_used', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cost_each', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory_item', ['container_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=32), nullable=True))
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cost_each')
        batch_op.drop_column('quantity_used')
        batch_op.drop_column('container_id')

    with op.batch_alter_table('batch_container', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cost_each')
        batch_op.drop_column('quantity_used')
        batch_op.drop_column('container_id')

    # ### end Alembic commands ###
