"""Add user tracking to models

Revision ID: 244c8a376a74
Revises: c0854ce07f82
Create Date: 2025-06-12 04:56:37.159480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244c8a376a74'
down_revision = 'c0854ce07f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_created_by', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('batch_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_ingredient_created_by', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('batch_inventory_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_inventory_log_created_by', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('product_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_event_created_by', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('product_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_inventory_created_by', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_inventory', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_inventory_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('product_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_event_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('batch_inventory_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batch_inventory_log_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('batch_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batch_ingredient_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batch_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
