"""Remove POS fields from InventoryHistory - raw inventory only

Revision ID: 2735cdaf1d0a
Revises: f76407232fa9
Create Date: 2025-06-26 19:32:34.167183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2735cdaf1d0a'
down_revision = 'f76407232fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserved', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
