"""Add perishable tracking fields to batch

Revision ID: 2af2ecb1908a
Revises: 67d6bd741153
Create Date: 2025-05-14 22:07:51.764271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af2ecb1908a'
down_revision = '67d6bd741153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_perishable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('batch_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_unit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_ingredient', schema=None) as batch_op:
        batch_op.drop_column('cost_per_unit')

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('shelf_life_days')
        batch_op.drop_column('is_perishable')

    # ### end Alembic commands ###
