
"""add_organization_support

Revision ID: 2b44df52e87b
Revises: 66320da1e92c
Create Date: 2025-06-13 20:35:37.232079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b44df52e87b'
down_revision = '66320da1e92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Organization table already exists from previous migration, just add foreign key
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_organization_id', 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_organization_id', type_='foreignkey')

    # ### end Alembic commands ###
