"""Update database schema

Revision ID: 3478c1df1783
Revises: 92228e3ede9f
Create Date: 2025-07-04 22:46:53.338345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3478c1df1783'
down_revision = '92228e3ede9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.alter_column('inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('unit_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.FLOAT(), nullable=True))
        batch_op.alter_column('inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
