"""Add reason field to ExtraBatchContainer

Revision ID: 3d0ff5b37467
Revises: 0c98c20f2100
Create Date: 2025-07-01 20:02:52.914369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0ff5b37467'
down_revision = '0c98c20f2100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('reason', sa.String(length=20), nullable=True))
    
    # Update existing records with default value
    op.execute("UPDATE extra_batch_container SET reason = 'extra_yield' WHERE reason IS NULL")
    
    # Now make it NOT NULL
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.alter_column('reason', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
