"""Increase password_hash length to 256

Revision ID: 3d46e754118a
Revises: 8a39f020e6ca
Create Date: 2025-07-26 05:48:47.534315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d46e754118a'
down_revision = '8a39f020e6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_barcode', ['barcode'])
        batch_op.create_unique_constraint('unique_upc', ['upc'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.drop_constraint('unique_upc', type_='unique')
        batch_op.drop_constraint('unique_barcode', type_='unique')

    # ### end Alembic commands ###
