"""add_fs_uniquifier_to_user

Revision ID: 40edebb0ba0e
Revises: 28f3476c0a52
Create Date: 2025-07-22 02:09:14.096767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40edebb0ba0e'
down_revision = '28f3476c0a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['flask_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_role_name_org', ['name', 'organization_id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('trial_days_remaining')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('_tag_name_org_uc', ['name', 'organization_id'])

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unit_name_org_uc', ['name', 'organization_id'])
        batch_op.create_index('ix_unit_standard_unique', ['name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_owner')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_login')
        batch_op.drop_column('subscription_class')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index('ix_user_preferences_organization_id')
        batch_op.drop_column('expiration_warning_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_warning_days', sa.INTEGER(), server_default=sa.text('3'), nullable=True))
        batch_op.create_index('ix_user_preferences_organization_id', ['organization_id'], unique=False)
        batch_op.alter_column('timezone',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_class', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_owner', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('active')
        batch_op.drop_column('password')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index('ix_unit_standard_unique')
        batch_op.drop_constraint('_unit_name_org_uc', type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('_tag_name_org_uc', type_='unique')
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_days_remaining', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_role_name_org', type_='unique')

    op.drop_table('roles_users')
    op.drop_table('flask_role')
    # ### end Alembic commands ###
