"""remove multiplier_to_base column from unit table

Revision ID: 45e872336209
Revises: 7266489529ec
Create Date: 2025-07-04 20:13:27.384662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e872336209'
down_revision = '7266489529ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('multiplier_to_base')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplier_to_base', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
