"""update_custom_unit_mapping_schema

Revision ID: 4ad10cd116e2
Revises: d71ecf3dfae9
Create Date: 2025-06-24 21:40:32.850716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad10cd116e2'
down_revision = 'd71ecf3dfae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_unit_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_unit', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('to_unit', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('multiplier', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ingredient_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('conversion_factor')
        batch_op.drop_column('unit_name')
        batch_op.drop_column('base_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_unit_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_unit', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('unit_name', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('conversion_factor', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ingredient_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('multiplier')
        batch_op.drop_column('to_unit')
        batch_op.drop_column('from_unit')

    # ### end Alembic commands ###
