"""empty message

Revision ID: 4f573215b665
Revises: 5adabbbfd04c
Create Date: 2025-05-21 15:35:15.073523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f573215b665'
down_revision = '5adabbbfd04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_history', ['fifo_reference_id'], ['id'])
        batch_op.drop_column('credited_to_fifo_id')
        batch_op.drop_column('source_fifo_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('shelf_life_days')

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('source_fifo_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('credited_to_fifo_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_history', ['source_fifo_id'], ['id'])
        batch_op.create_foreign_key(None, 'inventory_history', ['credited_to_fifo_id'], ['id'])

    # ### end Alembic commands ###
