"""Add is_archived column to inventory_item

Revision ID: 4ff7f4b5ea62
Revises: 8f63b86dc675
Create Date: 2025-05-22 16:07:29.019153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff7f4b5ea62'
down_revision = '8f63b86dc675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
