"""empty message

Revision ID: 55817f80cd34
Revises: 0010_recipe_status_drafts
Create Date: 2025-12-08 22:42:22.801168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55817f80cd34'
down_revision = '0010_recipe_status_drafts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batchbot_credit_bundle', schema=None) as batch_op:
        batch_op.drop_index('ix_batchbot_credit_bundle_addon_id')

    with op.batch_alter_table('global_item', schema=None) as batch_op:
        batch_op.drop_index('ix_global_item_active_type_name')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('recommended_usage_rate')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('recipe_sales_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('recipe_library_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('recipe_violation_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index('ix_unit_scope', ['is_active', 'is_custom', 'organization_id'], unique=False)
        batch_op.create_index('ix_unit_sort', ['unit_type', 'name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_organization_id', ['organization_id'], unique=False)

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index('ix_unit_sort')
        batch_op.drop_index('ix_unit_scope')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('recipe_violation_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('recipe_library_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('recipe_sales_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_usage_rate', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    with op.batch_alter_table('global_item', schema=None) as batch_op:
        batch_op.create_index('ix_global_item_active_type_name', ['is_archived', 'item_type', 'name'], unique=False)

    with op.batch_alter_table('batchbot_credit_bundle', schema=None) as batch_op:
        batch_op.create_index('ix_batchbot_credit_bundle_addon_id', ['addon_id'], unique=False)

    # ### end Alembic commands ###
