"""empty message

Revision ID: 57d6ce45a761
Revises: 6f9bc65166b3
Create Date: 2025-08-13 21:21:53.257392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d6ce45a761'
down_revision = '6f9bc65166b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed problematic drop_table operation for non-existent _alembic_tmp_batch_container
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed problematic create_table operation for _alembic_tmp_batch_container
    pass
    # ### end Alembic commands ###