"""Add is_custom field to Unit model

Revision ID: 59c114c36108
Revises: 4097d1f954b2
Create Date: 2025-04-22 16:59:32.895468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c114c36108'
down_revision = '4097d1f954b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_unit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('aliases', sa.TEXT(), nullable=True),
    sa.Column('base_equivalent', sa.FLOAT(), nullable=True),
    sa.Column('density_required', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
