"""Remove POS integration fields from InventoryItem - raw inventory cleanup

Revision ID: 70aede0fdb5f
Revises: 2735cdaf1d0a
Create Date: 2025-06-26 19:33:56.994352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70aede0fdb5f'
down_revision = '2735cdaf1d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('frozen_quantity')
        batch_op.drop_column('available_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('frozen_quantity', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
