"""add recipe snapshot column

Revision ID: 73212808b003
Revises: 67d6bd741153
Create Date: 2025-05-02 23:48:32.108693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73212808b003'
down_revision = '67d6bd741153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('recipe_snapshot')

    # ### end Alembic commands ###
