"""empty message

Revision ID: 73d7c827e3c3
Revises: 0005_cleanup_guardrails
Create Date: 2025-11-05 18:01:29.254352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d7c827e3c3'
down_revision = '0005_cleanup_guardrails'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_item', schema=None) as batch_op:
        batch_op.drop_column('shelf_life_months')

    with op.batch_alter_table('ingredient_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_shelf_life_days', sa.Boolean(), nullable=True))
        batch_op.drop_column('show_shelf_life_months')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_shelf_life_months', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('show_shelf_life_days')

    with op.batch_alter_table('global_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_life_months', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
