"""empty message

Revision ID: 7f24437584a7
Revises: 9cc730057642
Create Date: 2025-04-22 21:04:23.744668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f24437584a7'
down_revision = '9cc730057642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_item', ['inventory_item_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.create_foreign_key(None, 'inventory_item', ['inventory_item_id'], ['id'])
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
