"""Add intermediate ingredient support to inventory items

Revision ID: 84207ea041ca
Revises: 8b7120014eb3
Create Date: 2025-07-02 19:35:18.233377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84207ea041ca'
down_revision = '8b7120014eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intermediate', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_inventory_item_organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_item_organization_id', ['organization_id'], unique=False)
        batch_op.drop_column('intermediate')

    # ### end Alembic commands ###
