"""clean fix for expiration field

Revision ID: 870c684d438b
Revises: 975ef252131b
Create Date: 2025-04-22 21:10:44.505765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870c684d438b'
down_revision = '975ef252131b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'inventory_item', ['inventory_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_item', ['inventory_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
