"""Add size_label and container tracking to ProductInventory

Revision ID: 8dfa489d825b
Revises: 6c8625f51976
Create Date: 2025-05-30 23:42:41.203233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfa489d825b'
down_revision = '6c8625f51976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_cost_per_unit', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory_item', ['container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('batch_cost_per_unit')
        batch_op.drop_column('container_id')
        batch_op.drop_column('size_label')

    # ### end Alembic commands ###
