
"""Add fields to ExtraBatchContainer

Revision ID: 8f63b86dc675
Revises: 
Create Date: 2025-05-22 00:48:49.743505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f63b86dc675'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cost_each', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.drop_column('cost_each')
        batch_op.drop_column('quantity_used')

    # ### end Alembic commands ###
