"""add_output_type_to_batch

Revision ID: 8fcb0fda7b46
Revises: 4ff7f4b5ea62
Create Date: 2025-05-29 19:58:36.100460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcb0fda7b46'
down_revision = '4ff7f4b5ea62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_column('output_type')

    # ### end Alembic commands ###
