"""Create inventory history table

Revision ID: 923b23b7c7ba
Revises: merge_heads
Create Date: 2025-05-16 20:34:05.944376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923b23b7c7ba'
down_revision = 'merge_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('quantity_change', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('used_for_batch_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('cost_each', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['used_for_batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.drop_column('quantity_used')
        batch_op.drop_column('cost_each')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_each', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('quantity_used', sa.INTEGER(), nullable=False))

    op.drop_table('inventory_history')
    # ### end Alembic commands ###
