"""Add reserved quantity tracking and update product models

Revision ID: 9bc15ea2061a
Revises: remove_original_quantity
Create Date: 2025-07-08 21:28:32.444022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc15ea2061a'
down_revision = 'remove_original_quantity'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_barcode', ['barcode'])
        batch_op.create_unique_constraint('unique_upc', ['upc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.drop_constraint('unique_upc', type_='unique')
        batch_op.drop_constraint('unique_barcode', type_='unique')

    # ### end Alembic commands ###
