
"""remove_sku_from_product_variation

Revision ID: 9f94e312f365
Revises: b6f0301314ec
Create Date: 2025-06-17 03:41:14.691832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f94e312f365'
down_revision = 'b6f0301314ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before trying to drop it
    inspector = sa.inspect(op.get_bind())
    columns = [c['name'] for c in inspector.get_columns('product_variation')]
    
    if 'sku' in columns:
        with op.batch_alter_table('product_variation', schema=None) as batch_op:
            batch_op.drop_column('sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
