def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricing_snapshots', 'stripe_lookup_key',
                   existing_type=sa.String(length=64),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricing_snapshots', 'stripe_lookup_key',
                   existing_type=sa.String(length=64),
                   nullable=False)
    # ### end Alembic commands ###