
"""remove_sku_from_product_variation

Revision ID: [GENERATED_REVISION]
Revises: b6f0301314ec
Create Date: [GENERATED_DATE]

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '[GENERATED_REVISION]'
down_revision = 'b6f0301314ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.drop_column('sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
