"""rename_yield_to_projected_yield

Revision ID: a489c6978022
Revises: allow_null_perishable
Create Date: 2025-05-15 01:12:21.449708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a489c6978022'
down_revision = 'allow_null_perishable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projected_yield', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('projected_yield_unit', sa.String(length=50), nullable=True))
        batch_op.drop_column('yield_unit')
        batch_op.drop_column('yield_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yield_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('yield_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('projected_yield_unit')
        batch_op.drop_column('projected_yield')

    # ### end Alembic commands ###
