"""Add missing columns to product_inventory

Revision ID: a9fc03d8bf53
Revises: add_organization_scoping
Create Date: 2025-06-25 20:30:09.826776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fc03d8bf53'
down_revision = 'add_organization_scoping'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_inventory_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batch_inventory_log_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.drop_constraint('fk_extra_batch_container_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('extra_batch_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_extra_batch_ingredient_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('product_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('size_label', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_cost_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_product_inventory_container_id', 'inventory_item', ['container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('batch_cost_per_unit')
        batch_op.drop_column('container_id')
        batch_op.drop_column('sku')
        batch_op.drop_column('size_label')
        batch_op.drop_column('variant')

    with op.batch_alter_table('extra_batch_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_extra_batch_ingredient_organization_id', 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('extra_batch_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_extra_batch_container_organization_id', 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('batch_inventory_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_batch_inventory_log_organization_id', 'organization', ['organization_id'], ['id'])

    
    # ### end Alembic commands ###
