"""empty message

Revision ID: aa3f08b054e6
Revises: f1c9edd78b39
Create Date: 2025-05-20 16:50:52.759594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3f08b054e6'
down_revision = 'f1c9edd78b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_fifo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credited_to_fifo_id', sa.Integer(), nullable=True))
        batch_op.drop_index('idx_inventory_history_change_type')
        batch_op.drop_index('idx_inventory_history_timestamp')
        batch_op.create_foreign_key(None, 'inventory_history', ['source_fifo_id'], ['id'])
        batch_op.create_foreign_key(None, 'inventory_history', ['credited_to_fifo_id'], ['id'])

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_item_name')
        batch_op.drop_index('idx_inventory_item_type')
        batch_op.drop_column('perishable')

    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.drop_index('idx_product_variation_sku')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index('idx_recipe_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index('idx_recipe_name', ['name'], unique=False)

    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.create_index('idx_product_variation_sku', ['sku'], unique=False)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perishable', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('idx_inventory_item_type', ['type'], unique=False)
        batch_op.create_index('idx_inventory_item_name', ['name'], unique=False)

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_inventory_history_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_inventory_history_change_type', ['change_type'], unique=False)
        batch_op.drop_column('credited_to_fifo_id')
        batch_op.drop_column('source_fifo_id')

    # ### end Alembic commands ###
