
"""add unique constraint on stripe event id

Revision ID: add_unique_constraint_stripe
Revises: 'fix_product_sku_name_column'
Create Date: 2025-08-11 20:06:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_unique_constraint_stripe'
down_revision = 'fix_product_sku_name_column'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint on stripe_event.event_id
    op.create_unique_constraint('uq_stripe_event_event_id', 'stripe_event', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint on stripe_event.event_id
    op.drop_constraint('uq_stripe_event_event_id', 'stripe_event', type_='unique')
    # ### end Alembic commands ###
