
"""add missing product_variation columns

Revision ID: b2c3d4e5f678
Revises: a1b2c3d4e5f6
Create Date: 2025-06-05 01:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f678'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('marketplace_id', sa.String(length=128), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE product_variation SET is_active = 1 WHERE is_active IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.drop_column('marketplace_id')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
