def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.drop_column('wholesale_price')
        batch_op.drop_column('retail_price')
    # ### end Alembic commands ###