"""add unit_type column to unit table

Revision ID: be3cf5daaa4f
Revises: fix_nullable_constraints
Create Date: 2025-08-01 20:05:51.807718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3cf5daaa4f'
down_revision = 'fix_nullable_constraints'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_organization')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('unit_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=32), nullable=False))
        batch_op.alter_column('unit_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    op.create_table('_alembic_tmp_organization',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('signup_source', sa.VARCHAR(length=64), nullable=True),
    sa.Column('promo_code', sa.VARCHAR(length=32), nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=32), nullable=True),
    sa.Column('subscription_tier_id', sa.INTEGER(), nullable=True),
    sa.Column('subscription_tier', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['subscription_tier_id'], ['subscription_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
