
"""add variant active columns

Revision ID: c1d2e3f4g567
Revises: 71d39daeb32f
Create Date: 2025-06-05 01:36:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g567'
down_revision = '71d39daeb32f'
branch_labels = ('variantactive',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
        batch_op.add_column(sa.Column('marketplace_id', sa.String(length=128), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE product_variation SET is_active = 1 WHERE is_active IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.drop_column('marketplace_id')
        batch_op.drop_column('is_active')
        batch_op.drop_column('wholesale_price')
        batch_op.drop_column('retail_price')
    # ### end Alembic commands ###
