"""add_product_variant_columns_to_batch

Revision ID: c9c3fea4ce10
Revises: add_product_foreign_keys
Create Date: 2025-07-03 23:15:39.221799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c3fea4ce10'
down_revision = 'add_product_foreign_keys'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_unit', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('low_stock_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_discontinued', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('shopify_product_id', sa.String(length=64), nullable=True),
    sa.Column('etsy_shop_section_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_organization_id'), ['organization_id'], unique=False)

    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='unique_product_variant')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index('idx_product_variant', ['product_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('variant_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_index('idx_product_name')
        batch_op.drop_index('idx_variant_name')
        batch_op.drop_constraint('unique_sku_fifo_combination', type_='unique')
        batch_op.create_unique_constraint('unique_sku_fifo_combination', ['product_id', 'variant_id', 'size_label', 'fifo_id'])
        batch_op.create_index('idx_legacy_product_name', ['product_name'], unique=False)
        batch_op.create_index('idx_legacy_variant_name', ['variant_name'], unique=False)
        batch_op.create_index('idx_product_variant', ['product_id', 'variant_id'], unique=False)
        batch_op.create_unique_constraint('unique_barcode', ['barcode'])
        batch_op.create_unique_constraint('unique_upc', ['upc'])
        batch_op.create_foreign_key(None, 'product_variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sku', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_upc', type_='unique')
        batch_op.drop_constraint('unique_barcode', type_='unique')
        batch_op.drop_index('idx_product_variant')
        batch_op.drop_index('idx_legacy_variant_name')
        batch_op.drop_index('idx_legacy_product_name')
        batch_op.drop_constraint('unique_sku_fifo_combination', type_='unique')
        batch_op.create_unique_constraint('unique_sku_fifo_combination', ['product_name', 'variant_name', 'size_label', 'fifo_id'])
        batch_op.create_index('idx_variant_name', ['variant_name'], unique=False)
        batch_op.create_index('idx_product_name', ['product_name'], unique=False)
        batch_op.alter_column('variant_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variant_id')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_organization_id'))
        batch_op.drop_index('idx_product_variant')

    op.drop_table('product_variant')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_organization_id'))

    op.drop_table('product')
    # ### end Alembic commands ###
