
"""remove_trial_tier_field

Revision ID: d93704a0817e
Revises: remove_organization_timezone
Create Date: 2025-07-21 23:07:35.136283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93704a0817e'
down_revision = 'remove_organization_timezone'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip index drops - these may not exist in current schema
    
    # Note: Skipping all organization_id index drops as they may not exist

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_role_name_org', ['name', 'organization_id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    # Skip subscription table changes - trial_days_remaining was already removed in fd6ec9059553

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('_tag_name_org_uc', ['name', 'organization_id'])

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_unique_constraint('_unit_name_org_uc', ['name', 'organization_id'])
        batch_op.create_index('ix_unit_standard_unique', ['name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_class')
        batch_op.drop_column('is_owner')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index('ix_user_preferences_organization_id')
        batch_op.drop_column('expiration_warning_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_warning_days', sa.INTEGER(), server_default=sa.text('3'), nullable=True))
        # Skip index creation - may cause conflicts
        batch_op.alter_column('timezone',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('subscription_class', sa.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index('ix_unit_standard_unique')
        batch_op.drop_constraint('_unit_name_org_uc', type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('_tag_name_org_uc', type_='unique')
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    # Skip subscription table changes

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_role_name_org', type_='unique')

    # Skip all organization_id index recreation - may cause conflicts

    # ### end Alembic commands ###
