"""Add quantity_used and used_for_batch_id to InventoryHistory

Revision ID: dc2034e4443f
Revises: add_missing_inventory_fields
Create Date: 2025-06-24 23:36:23.739719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2034e4443f'
down_revision = 'add_missing_inventory_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('used_for_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'batch', ['used_for_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('used_for_batch_id')
        batch_op.drop_column('quantity_used')

    # ### end Alembic commands ###
