"""Clean SubscriptionTier model - use lookup keys only, remove hardcoded price IDs

Revision ID: e0c3f7e2036e
Revises: clean_subscription_tier_billing
Create Date: 2024-08-06 19:52:56.789123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e0c3f7e2036e'
down_revision = 'clean_subscription_tier_billing'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safety check: only drop the table if it exists
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    if '_alembic_tmp_subscription_tier' in inspector.get_table_names():
        op.drop_table('_alembic_tmp_subscription_tier')
    with op.batch_alter_table('subscription_tier', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
        batch_op.alter_column('user_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_monthly_batches',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_customer_facing',
               existing_type=sa.NUMERIC(),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.alter_column('billing_provider',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.alter_column('is_billing_exempt',
               existing_type=sa.NUMERIC(),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.alter_column('stripe_lookup_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('whop_product_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('fallback_price',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('ix_subscription_tier_key')
        batch_op.create_index(batch_op.f('ix_subscription_tier_is_billing_exempt'), ['is_billing_exempt'], unique=False)
        batch_op.create_unique_constraint(None, ['whop_product_key'])
        batch_op.create_unique_constraint(None, ['key'])
        batch_op.create_unique_constraint(None, ['stripe_lookup_key'])
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('tier_key')
        batch_op.drop_column('stripe_price_id_yearly')
        batch_op.drop_column('stripe_price_id_monthly')
        batch_op.drop_column('grace_period_days')
        batch_op.drop_column('last_billing_sync')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_tier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_billing_sync', sa.NUMERIC(), nullable=True))
        batch_op.add_column(sa.Column('grace_period_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id_monthly', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id_yearly', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tier_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('stripe_product_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_subscription_tier_is_billing_exempt'))
        batch_op.create_index('ix_subscription_tier_key', ['key'], unique=1)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('fallback_price',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('whop_product_key',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('stripe_lookup_key',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_billing_exempt',
               existing_type=sa.Boolean(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('billing_provider',
               existing_type=sa.NullType(),
               nullable=True)
        batch_op.alter_column('is_customer_facing',
               existing_type=sa.Boolean(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('max_monthly_batches',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('key',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_subscription_tier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('key', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_limit', sa.INTEGER(), nullable=True),
    sa.Column('is_customer_facing', sa.BOOLEAN(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.Column('stripe_lookup_key', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('whop_product_key', sa.VARCHAR(length=128), nullable=True),
    sa.Column('fallback_price', sa.VARCHAR(length=32), nullable=True),
    sa.Column('last_billing_sync', sa.DATETIME(), nullable=True),
    sa.Column('grace_period_days', sa.INTEGER(), nullable=True),
    sa.Column('tier_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('billing_provider', sa.VARCHAR(length=32), server_default=sa.text("'exempt'"), nullable=False),
    sa.Column('tier_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('max_users', sa.INTEGER(), nullable=False),
    sa.Column('max_monthly_batches', sa.INTEGER(), nullable=False),
    sa.Column('stripe_product_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('stripe_price_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.VARCHAR(length=128), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_billing_exempt', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###