"""add is_extra field to batch containers

Revision ID: ea7195e1636d
Revises: fb02322afb52
Create Date: 2025-05-07 22:57:13.091979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7195e1636d'
down_revision = 'fb02322afb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_extra', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_container', schema=None) as batch_op:
        batch_op.drop_column('is_extra')

    # ### end Alembic commands ###
