"""add_fifo_tracking_columns

Revision ID: f1c9edd78b39
Revises: update_inventory_tracking
Create Date: 2025-05-20 16:48:37.825248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c9edd78b39'
down_revision = 'update_inventory_tracking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_index('idx_batch_label_code')
        batch_op.drop_index('idx_batch_started_at')
        batch_op.drop_index('idx_batch_status')

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_fifo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credited_to_fifo_id', sa.Integer(), nullable=True))
        batch_op.drop_index('idx_inventory_history_change_type')
        batch_op.drop_index('idx_inventory_history_timestamp')
        batch_op.create_foreign_key(None, 'inventory_history', ['source_fifo_id'], ['id'])
        batch_op.create_foreign_key(None, 'inventory_history', ['credited_to_fifo_id'], ['id'])

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_item_name')
        batch_op.drop_index('idx_inventory_item_type')
        batch_op.drop_column('perishable')

    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.drop_index('idx_product_variation_sku')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index('idx_recipe_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index('idx_recipe_name', ['name'], unique=False)

    with op.batch_alter_table('product_variation', schema=None) as batch_op:
        batch_op.create_index('idx_product_variation_sku', ['sku'], unique=False)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perishable', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('idx_inventory_item_type', ['type'], unique=False)
        batch_op.create_index('idx_inventory_item_name', ['name'], unique=False)

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_inventory_history_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_inventory_history_change_type', ['change_type'], unique=False)
        batch_op.drop_column('credited_to_fifo_id')
        batch_op.drop_column('source_fifo_id')

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.create_index('idx_batch_status', ['status'], unique=False)
        batch_op.create_index('idx_batch_started_at', ['started_at'], unique=False)
        batch_op.create_index('idx_batch_label_code', ['label_code'], unique=False)

    # ### end Alembic commands ###
