"""add_user_type_column

Revision ID: f6a9b50d9a17
Revises: 6e0c5e2e1c48
Create Date: 2025-07-11 03:28:10.848583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a9b50d9a17'
down_revision = '6e0c5e2e1c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Check if user_type column already exists
        try:
            batch_op.add_column(sa.Column('user_type', sa.String(length=32), nullable=True))
        except Exception as e:
            if "duplicate column name: user_type" in str(e):
                print("user_type column already exists, skipping...")
            else:
                raise e
        
        # Check if is_active column already exists
        try:
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        except Exception as e:
            if "duplicate column name: is_active" in str(e):
                print("is_active column already exists, skipping...")
            else:
                raise e

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_user_preferences_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_organization_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
