
"""Remove reason field from ExtraBatchIngredient

Revision ID: remove_reason_ingredient
Revises: ce3f2d2a05cf
Create Date: 2025-07-01 23:32:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_reason_ingredient'
down_revision = 'ce3f2d2a05cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_ingredient', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_batch_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=20), nullable=False, default='extra_needed'))

    # ### end Alembic commands ###
