"""Curated taxonomy constants per SOP (2025 edition)."""

from __future__ import annotations

# Primary base-level ingredient categories (assigned to the BASE; single-select).
INGREDIENT_CATEGORIES_PRIMARY: list[str] = [
    "Fruits & Berries",
    "Vegetables",
    "Grains",
    "Nuts",
    "Seeds",
    "Spices",
    "Herbs",
    "Flowers",
    "Roots",
    "Barks",
    "Clays",
    "Minerals",
    "Salts",
    "Sugars",
    "Liquid Sweeteners",
    "Acids",
]

# Master Categories (UX dropdown multi-select; curated group).
# NOTE: user-provided list exceeds "28"; we keep exactly as provided.
MASTER_CATEGORIES: list[str] = [
    "Fruits & Berries",
    "Vegetables",
    "Grains & Starches",
    "Nuts",
    "Seeds",
    "Spices",
    "Herbs",
    "Flowers",
    "Roots",
    "Barks",
    "Oils & Fats",
    "Carriers",
    "Butters",
    "Waxes",
    "Essential Oils",
    "Extracts",
    "Absolutes",
    "Concretes",
    "Resins & Gums",
    "Hydrosols",
    "Clays",
    "Minerals",
    "Salts",
    "Colorants & Pigmants",
    "Preservatives & Antioxidants",
    "Surfactants & Cleansers",
    "Emulsifiers & Stabilizers",
    "Thickeners & Gelling Agents",
    "Fermentation Starters",
    "Sugars",
    "Liquid Sweeteners",
    "Acids & PH Adjusters",
]

ORIGINS: list[str] = [
    "Plant-Derived",
    "Animal-Derived",
    "Animal-Byproduct",
    "Mineral/Earth",
    "Synthetic",
    "Fermentation",
    "Marine-Derived",
]

REFINEMENT_LEVELS: list[str] = [
    "Raw/Unprocessed",
    "Minimally Processed",
    "Extracted/Distilled",
    "Milled/Ground",
    "Fermented",
    "Synthesized",
    "Extracted Fat",
    "Other",
]

# Item-level curated variations (grows with review).
VARIATIONS_CURATED: list[str] = [
    "Essential",
    "CO2 Extracted",
    "Raw",
    "2%",
    "Granulated",
    "Refined",
    "Unrefined",
    "White",
    "Whole",
    "Brown",
    "Dutch-Processed",
    "Organic",
    "Filtered",
    "Unsweetened",
    "Cold-Pressed",
    "Steam-Distilled",
    "Micronized",
    "Nano",
    "Food-Grade",
    "Barista",
    "Low-Fat",
    "Reduced",
    "Crystallized",
    "Powdered",
    "Chunky",
    "Cinnamon",
    "Salted",
    "Anhydrous",
    "Hydrous",
    "Creamed",
    "Fair Trade",
    "Kosher",
    "GMO-Free",
    "Grade A",
    "Sweet",
    "Bitter",
    "Kappa",
    "Methylcobalamin",
    "Hydrated",
    "Unbleached",
    "Bleached",
    "Whole Grain",
    "Enriched",
    "Fortified",
    "Instant",
    "Slow-Rise",
    "Active Dry",
    "Fresh",
    # Structural variations used for master-category derivation / item modeling.
    # These are distinct from physical_form and may appear as the purchasable "type".
    "Oil",
    "Butter",
    "Wax",
    "Essential Oil",
    "CO2 Extract",
    "Extract",
    "Absolute",
    "Concrete",
]

PHYSICAL_FORMS: list[str] = [
    "Whole",
    "Slices",
    "Diced",
    "Chopped",
    "Minced",
    "Crushed",
    "Ground",
    "Powder",
    "Granules",
    "Flakes",
    "Shreds",
    "Ribbons",
    "Pellets",
    "Chips",
    "Nib",
    "Buds",
    "Flowers",
    "Leaves",
    "Needles",
    "Stems",
    "Bark",
    "Resin",
    "Gum",
    "Latex",
    "Sap",
    "Juice",
    "Puree",
    "Paste",
    "Concentrate",
    "Syrup",
    "Infusion",
    "Decoction",
    "Tincture",
    "Hydrosol",
    "Oil",
    "Butter",
    "Wax",
    "Crystals",
    "Isolate",
    "Emulsion",
]

# Seeded rules that connect existing vocab into the Master Categories (UX group).
# Each tuple: (master_category, source_type, source_value)
# source_type in: ingredient_category | variation | physical_form | function_tag | application
MASTER_CATEGORY_RULE_SEED: list[tuple[str, str, str]] = [
    # Ingredient category -> master category (identity, with a couple of remaps)
    ("Fruits & Berries", "ingredient_category", "Fruits & Berries"),
    ("Vegetables", "ingredient_category", "Vegetables"),
    ("Grains & Starches", "ingredient_category", "Grains"),
    ("Nuts", "ingredient_category", "Nuts"),
    ("Seeds", "ingredient_category", "Seeds"),
    ("Spices", "ingredient_category", "Spices"),
    ("Herbs", "ingredient_category", "Herbs"),
    ("Flowers", "ingredient_category", "Flowers"),
    ("Roots", "ingredient_category", "Roots"),
    ("Barks", "ingredient_category", "Barks"),
    ("Clays", "ingredient_category", "Clays"),
    ("Minerals", "ingredient_category", "Minerals"),
    ("Salts", "ingredient_category", "Salts"),
    ("Sugars", "ingredient_category", "Sugars"),
    ("Liquid Sweeteners", "ingredient_category", "Liquid Sweeteners"),
    ("Acids & PH Adjusters", "ingredient_category", "Acids"),

    # Physical forms -> master categories
    ("Oils & Fats", "physical_form", "Oil"),
    ("Carriers", "physical_form", "Oil"),
    ("Butters", "physical_form", "Butter"),
    ("Waxes", "physical_form", "Wax"),
    ("Hydrosols", "physical_form", "Hydrosol"),
    ("Resins & Gums", "physical_form", "Resin"),
    ("Resins & Gums", "physical_form", "Gum"),

    # Variations -> master categories
    ("Essential Oils", "variation", "Essential Oil"),
    ("Essential Oils", "variation", "Steam-Distilled"),
    ("Extracts", "variation", "CO2 Extracted"),
    ("Extracts", "variation", "CO2 Extract"),
    ("Extracts", "variation", "Extract"),
    ("Absolutes", "variation", "Absolute"),
    ("Concretes", "variation", "Concrete"),

    # Function tags -> master categories
    ("Colorants & Pigmants", "function_tag", "Colorant"),
    ("Preservatives & Antioxidants", "function_tag", "Preservative"),
    ("Preservatives & Antioxidants", "function_tag", "Antioxidant"),
    ("Surfactants & Cleansers", "function_tag", "Surfactant"),
    ("Emulsifiers & Stabilizers", "function_tag", "Emulsifier"),
    ("Emulsifiers & Stabilizers", "function_tag", "Stabilizer"),
    ("Thickeners & Gelling Agents", "function_tag", "Thickener"),
]

