"""Curated taxonomy constants per SOP (2025 edition)."""

from __future__ import annotations

# Primary base-level ingredient categories (assigned to the BASE; single-select).
INGREDIENT_CATEGORIES_PRIMARY: list[str] = [
    "Fruits & Berries",
    "Vegetables",
    "Grains",
    "Nuts",
    "Seeds",
    "Spices",
    "Herbs",
    "Flowers",
    "Roots",
    "Barks",
    "Clays",
    "Minerals",
    "Salts",
    "Sugars",
    "Liquid Sweeteners",
    "Acids",
]

# Master Categories (UX dropdown multi-select; curated group).
# NOTE: user-provided list exceeds "28"; we keep exactly as provided.
MASTER_CATEGORIES: list[str] = [
    "Fruits & Berries",
    "Vegetables",
    "Grains & Starches",
    "Nuts",
    "Seeds",
    "Spices",
    "Herbs",
    "Flowers",
    "Roots",
    "Barks",
    "Oils & Fats",
    "Carriers",
    "Butters",
    "Waxes",
    "Essential Oils",
    "Extracts",
    "Absolutes",
    "Concretes",
    "Resins & Gums",
    "Hydrosols",
    "Clays",
    "Minerals",
    "Salts",
    "Colorants & Pigmants",
    "Preservatives & Antioxidants",
    "Surfactants & Cleansers",
    "Emulsifiers & Stabilizers",
    "Thickeners & Gelling Agents",
    "Fermentation Starters",
    "Sugars",
    "Liquid Sweeteners",
    "Acids & PH Adjusters",
]

ORIGINS: list[str] = [
    "Plant-Derived",
    "Animal-Derived",
    "Animal-Byproduct",
    "Mineral/Earth",
    "Synthetic",
    "Fermentation",
    "Marine-Derived",
]

REFINEMENT_LEVELS: list[str] = [
    "Raw/Unprocessed",
    "Minimally Processed",
    "Extracted/Distilled",
    "Milled/Ground",
    "Fermented",
    "Synthesized",
    "Extracted Fat",
    "Other",
]

# Item-level curated variations (grows with review).
VARIATIONS_CURATED: list[str] = [
    "Essential",
    "CO2 Extracted",
    "Raw",
    "2%",
    "Granulated",
    "Refined",
    "Unrefined",
    "White",
    "Whole",
    "Brown",
    "Dutch-Processed",
    "Organic",
    "Filtered",
    "Unsweetened",
    "Cold-Pressed",
    "Steam-Distilled",
    "Micronized",
    "Nano",
    "Food-Grade",
    "Barista",
    "Low-Fat",
    "Reduced",
    "Crystallized",
    "Powdered",
    "Chunky",
    "Cinnamon",
    "Salted",
    "Anhydrous",
    "Hydrous",
    "Creamed",
    "Fair Trade",
    "Kosher",
    "GMO-Free",
    "Grade A",
    "Sweet",
    "Bitter",
    "Kappa",
    "Methylcobalamin",
    "Hydrated",
    "Unbleached",
    "Bleached",
    "Whole Grain",
    "Enriched",
    "Fortified",
    "Instant",
    "Slow-Rise",
    "Active Dry",
    "Fresh",
]

PHYSICAL_FORMS: list[str] = [
    "Whole",
    "Slices",
    "Diced",
    "Chopped",
    "Minced",
    "Crushed",
    "Ground",
    "Powder",
    "Granules",
    "Flakes",
    "Shreds",
    "Ribbons",
    "Pellets",
    "Chips",
    "Nib",
    "Buds",
    "Flowers",
    "Leaves",
    "Needles",
    "Stems",
    "Bark",
    "Resin",
    "Gum",
    "Latex",
    "Sap",
    "Juice",
    "Puree",
    "Paste",
    "Concentrate",
    "Syrup",
    "Infusion",
    "Decoction",
    "Tincture",
    "Hydrosol",
    "Oil",
    "Butter",
    "Wax",
    "Crystals",
    "Isolate",
    "Emulsion",
]

