name: Migration Heads & Sequence Check
on: [push, pull_request]

jobs:
  heads-and-sequence:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: wsgi:app
      PYTHONPATH: ${{ github.workspace }}
      SQLALCHEMY_DISABLE_CREATE_ALL: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Check for multiple heads
        shell: bash
        run: |
          export DATABASE_URL="sqlite:///$(mktemp -u).db"
          flask db upgrade
          heads_count="$(flask db heads | wc -l)"
          if [ "$heads_count" -gt 1 ]; then
            echo "❌ Multiple migration heads detected!" 
            flask db heads
            exit 1
          fi
          echo "✅ Single migration head confirmed."

      - name: Validate migration sequence (upgrade/downgrade)
        shell: bash
        run: |
          export DATABASE_URL="sqlite:///$(mktemp -u).db"
          echo "🔄 Testing full migration sequence..."
          flask db upgrade
          current_head=$(flask db current)
          if [ -n "$current_head" ]; then
            echo "📉 Testing downgrade of last step then re-upgrade..."
            flask db downgrade -1
            flask db upgrade
            echo "✅ Migration reversibility confirmed"
          fi
          echo "✅ Migration sequence validation complete"
